services:
  sim2:
    image: f1tenth_code:latest
    build: ./
    volumes:
      - .:/sim_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=novnc2:0.0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      - ROS_DOMAIN_ID=0
      - ROS_NAMESPACE=sim2
      - SDL_GAMECONTROLLERCONFIG=${SDL_GAMECONTROLLERCONFIG:-}
    privileged: true
    networks:
      - x11
      - ros_net
    stdin_open: true
    tty: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  novnc2:
    # NoVNC container for the second simulator
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - VNC_QUALITY=80
      - VNC_COMPRESSION=9
    ports:
      - "8081:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - x11

networks:
  x11:
  ros_net:
    # External network flag allows sharing between compose files
    external: true
    name: ros_net