
services:
  sim2:
    # Second simulator container using f1tenth_gustavo image
    image: f1tenth_gustavo
    build: ./
    volumes:
      - .:/sim_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      # Display settings for X11 forwarding through NoVNC
      - DISPLAY=novnc2:0.0
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.Xauthority
      # ROS2 configuration matching the first simulator
      - ROS_DOMAIN_ID=0
      - ROS_NAMESPACE=sim2
    networks:
      - x11
      - ros_net
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined

  novnc2:
    # NoVNC container for the second simulator
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
      - VNC_QUALITY=80
      - VNC_COMPRESSION=9
    ports:
      - "8081:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - x11

networks:
  x11:
  ros_net:
    # External network flag allows sharing between compose files
    external: true
    name: ros_net