# QoS Configuration for F1Tenth Cross-Platform SLAM
cartographer_node:
  ros__parameters:
    qos_overrides:
      /scan:
        subscription:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 5