local_planner:
  ros__parameters:
    # Grade de ocupação
    grid_size: 20.0
    resolution: 0.05
    
    # Parâmetros RRT
    max_samples: 200
    step_size: 0.5
    goal_sample_rate: 0.2
    search_radius: 0.5
    
    # Parâmetros de controle
    max_speed: 2.0
    max_steer: 0.4
    lookahead: 1.0
    
    # Tópicos
    scan_topic: "/scan"
    pose_topic: "/ego_racecar/odom"
    cmd_vel_topic: "/cmd_vel"